DROP TABLE IF EXISTS VETS;
DROP TABLE IF EXISTS ANIMAL_TYPES;
DROP TABLE IF EXISTS PETS;
DROP TABLE IF EXISTS APPOINTMENTS;

CREATE TABLE VETS
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE INDEX IDX_VETS_NAME ON VETS (name);

CREATE TABLE ANIMAL_TYPES
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE INDEX IDX_ANIMAL_TYPES_NAME ON ANIMAL_TYPES (name);

CREATE TABLE PETS
(
    id             INT AUTO_INCREMENT PRIMARY KEY,
    name           VARCHAR(250) NOT NULL,
    vet_id         INT          NOT NULL,
    animal_type_id INT          NOT NULL
);

CREATE INDEX IDX_PETS_NAME ON PETS (name);

CREATE TABLE APPOINTMENTS
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    start  TIMESTAMP NOT NULL,
    end    TIMESTAMP NOT NULL,
    pet_id INT       NOT NULL
);

